name: tj_inventory


services:
  django:
    # build: ./django
    image: tj_inventory_dev-django:latest
    container_name: django
    restart: always
    environment:
      - DATABASE_TYPE=postgres
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - DEBUG=${DEBUG}
      - EXPRESS_LOCATION=${EXPRESS_LOCATION}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - "${DJANGO_MEDIA}:/app/media:rw"
    ports:
      - "${DJANGO_HOST_PRD_PORT}:${DJANGO_PORT}"
    networks:
      - tj_inventory
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgres:15.17-alpine3.22
    container_name: postgres
    restart: always
    shm_size: 128m
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tj_inventory

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "${ADMINER_HOST_PRD_PORT}:8080"
    networks:
      - tj_inventory
    depends_on:
      postgres:
        condition: service_started


volumes:
  postgres_data:
    name: tj_inventory_postgres_data
    external: true


networks:
  tj_inventory:
    driver: bridge
