services:
  django:
    build: ./django
    container_name: django
    restart: always
    # env_file:
    #   - ./secrets/django.env
    #   - ./secrets/db.env
    environment:
      - DATABASE_TYPE=postgres
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - DEBUG=${DEBUG}
      - EXPRESS_LOCATION=${EXPRESS_LOCATION}
      - COMPANY_WAREHOUSE_CODES=${COMPANY_WAREHOUSE_CODES}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    # volumes:
      # - ./django/srcs:/app
      # - ./django/migrate:/migrate
      # - ./django/srcs/media:/app/media
    ports:
      - "8000:8000"
    networks:
      - tj_inventory
    depends_on:
      - db

  db:
    image: postgres:15.17-alpine3.22
    container_name: postgres
    restart: always
    shm_size: 128m
    # env_file:
    #   - ./secrets/db.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    networks:
      - tj_inventory

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - tj_inventory
    depends_on:
      - db

volumes:
  postgres_data:
    name: tj_inventory_postgres_data
    external: true

networks:
  tj_inventory:
    driver: bridge
