name: tj_inventory_dev


services:
  db-init:
    image: alpine:latest
    container_name: tj_inventory_db-init_dev
    volumes:
      - ./db-init/db_sync.sh:/db_sync.sh:ro
    environment:
      - REFRESH_DB_DEV=${REFRESH_DB_DEV:-false}
      - PROD_SSH_HOST=${PROD_SSH_HOST}
      - PROD_SSH_USER=${PROD_SSH_USER}
      - PROD_SSH_PASSWORD=${PROD_SSH_PASSWORD}
      - PROD_SSH_PORT=${PROD_SSH_PORT:-22}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: sh /db_sync.sh
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tj_inventory_dev

  django:
    build: ./django
    container_name: django_dev
    restart: always
    environment:
      - DATABASE_TYPE=postgres
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - DEBUG=${DEBUG}
      - EXPRESS_LOCATION=${EXPRESS_LOCATION}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - ~/win-work/tj_inventory/django/srcs:/app # Uncomment for local hot-reload dev, comment out/remove for Portainer
    ports:
      - "${DJANGO_HOST_DEV_PORT}:${DJANGO_PORT}"
    networks:
      - tj_inventory_dev
    depends_on:
      db-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15.17-alpine3.22
    container_name: postgres_dev
    restart: always
    shm_size: 128m
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - tj_inventory_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: adminer_dev
    restart: always
    ports:
      - "${ADMINER_HOST_DEV_PORT}:8080"
    networks:
      - tj_inventory_dev
    depends_on:
      postgres:
        condition: service_started

volumes:
  postgres_data_dev:
    

networks:
  tj_inventory_dev:
    driver: bridge
