# Generated by Django 5.2.12 on 2026-07-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashpaymentitem',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='TAX amount associated with this item', max_digits=12, null=True),
        ),
    ]
