# Generated by Django 5.2.12 on 2026-07-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_pettycashpaymentitem_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpettycashpayment',
            name='external_pv_no',
            field=models.CharField(blank=True, default='', help_text='External Express PV (Payment Voucher) number if created directly in Express.', max_length=100),
        ),
        migrations.AddField(
            model_name='pettycashpayment',
            name='external_pv_no',
            field=models.CharField(blank=True, default='', help_text='External Express PV (Payment Voucher) number if created directly in Express.', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalpettycashpayment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of all payment line amounts and tax', max_digits=12),
        ),
        migrations.AlterField(
            model_name='pettycashpayment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of all payment line amounts and tax', max_digits=12),
        ),
    ]
