# Generated by Django 5.2.12 on 2026-07-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_historicalpettycashpayment_external_pv_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpettycashaccount',
            name='rounding_category_code',
            field=models.CharField(default='4200-07', help_text='GL Chart of Accounts category code for rounding adjustments', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalpettycashaccount',
            name='vat_category_code',
            field=models.CharField(default='1155-00', help_text='GL Chart of Accounts category code for undue input VAT', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalpettycashpayment',
            name='rounding_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Adjustment to round replenishment amount to integer', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pettycashaccount',
            name='rounding_category_code',
            field=models.CharField(default='4200-07', help_text='GL Chart of Accounts category code for rounding adjustments', max_length=20),
        ),
        migrations.AddField(
            model_name='pettycashaccount',
            name='vat_category_code',
            field=models.CharField(default='1155-00', help_text='GL Chart of Accounts category code for undue input VAT', max_length=20),
        ),
        migrations.AddField(
            model_name='pettycashpayment',
            name='rounding_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Adjustment to round replenishment amount to integer', max_digits=12, null=True),
        ),
    ]
