# Generated by Django 5.2.12 on 2026-07-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_historicalpettycashaccount_rounding_category_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpettycashpayment',
            name='external_pv_no',
        ),
        migrations.RemoveField(
            model_name='historicalpettycashpayment',
            name='rounding_adjustment',
        ),
        migrations.RemoveField(
            model_name='pettycashpayment',
            name='external_pv_no',
        ),
        migrations.RemoveField(
            model_name='pettycashpayment',
            name='rounding_adjustment',
        ),
        migrations.AddField(
            model_name='pettycashpaymentitem',
            name='external_pv_no',
            field=models.CharField(blank=True, default='', help_text='External Express PV (Payment Voucher) number if created directly in Express.', max_length=100),
        ),
        migrations.AddField(
            model_name='pettycashpaymentitem',
            name='rounding_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Adjustment to round this item to integer', max_digits=12, null=True),
        ),
    ]
