# Generated by Django 5.2.12 on 2026-03-31 04:30

import catalog.models.item_image
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Record status (active/inactive)', max_length=20)),
                ('sku', models.CharField(db_index=True, help_text='Unique internal SKU code', max_length=50)),
                ('express_sku', models.CharField(blank=True, db_index=True, default='', help_text='SKU code for Express system sync (optional)', max_length=50)),
                ('name', models.CharField(help_text='Item display name', max_length=200)),
                ('unit', models.CharField(help_text='Unit of measurement (e.g. pcs, kg, box)', max_length=50)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed product description')),
                ('note', models.TextField(blank=True, default='', help_text='Internal notes about this item')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, help_text='Category this item belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.category')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical item',
                'verbose_name_plural': 'historical items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Record status (active/inactive)', max_length=20)),
                ('sku', models.CharField(db_index=True, help_text='Unique internal SKU code', max_length=50, unique=True)),
                ('express_sku', models.CharField(blank=True, db_index=True, default='', help_text='SKU code for Express system sync (optional)', max_length=50)),
                ('name', models.CharField(help_text='Item display name', max_length=200)),
                ('unit', models.CharField(help_text='Unit of measurement (e.g. pcs, kg, box)', max_length=50)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed product description')),
                ('note', models.TextField(blank=True, default='', help_text='Internal notes about this item')),
                ('category', models.ForeignKey(blank=True, help_text='Category this item belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.category')),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalItemImage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Record status (active/inactive)', max_length=20)),
                ('image', models.TextField(help_text='Image file for the item', max_length=100)),
                ('is_main', models.BooleanField(default=False, help_text='Mark as the main/primary image for the item')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('note', models.TextField(blank=True, default='', help_text='Optional caption or note for this image')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, help_text='The item this image belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.item')),
            ],
            options={
                'verbose_name': 'historical item image',
                'verbose_name_plural': 'historical item images',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Record status (active/inactive)', max_length=20)),
                ('image', models.ImageField(help_text='Image file for the item', upload_to=catalog.models.item_image.item_image_upload_path)),
                ('is_main', models.BooleanField(default=False, help_text='Mark as the main/primary image for the item')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('note', models.TextField(blank=True, default='', help_text='Optional caption or note for this image')),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(help_text='The item this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.item')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_main', 'sort_order', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='catalog_ite_name_9b7e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='itemimage',
            index=models.Index(fields=['item', 'is_main'], name='catalog_ite_item_id_328f9d_idx'),
        ),
    ]
