# Generated by Django 5.2.12 on 2026-04-01 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_historicalitem_item_historicalitemimage_itemimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimage',
            options={'ordering': ['-is_main', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalitemimage',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='itemimage',
            name='sort_order',
        ),
    ]
