# Generated by Django 5.2.12 on 2026-05-18 04:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_historicalitem_name2_item_name2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalItemPackaging',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Record status (active/inactive)', max_length=20)),
                ('name', models.CharField(help_text='Packaging name (e.g., Carton, Box, Dozen, Pallet)', max_length=50)),
                ('quantity', models.PositiveIntegerField(help_text='Number of base units (pieces) contained in this packaging')),
                ('barcode', models.CharField(blank=True, default='', help_text='Optional barcode specific to this packaging unit', max_length=100)),
                ('note', models.TextField(blank=True, default='', help_text='Optional internal notes about this packaging')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, help_text='The item this packaging belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.item')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical item packaging',
                'verbose_name_plural': 'historical item packagings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ItemPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Record status (active/inactive)', max_length=20)),
                ('name', models.CharField(help_text='Packaging name (e.g., Carton, Box, Dozen, Pallet)', max_length=50)),
                ('quantity', models.PositiveIntegerField(help_text='Number of base units (pieces) contained in this packaging')),
                ('barcode', models.CharField(blank=True, default='', help_text='Optional barcode specific to this packaging unit', max_length=100)),
                ('note', models.TextField(blank=True, default='', help_text='Optional internal notes about this packaging')),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(help_text='The item this packaging belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='packagings', to='catalog.item')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item', 'quantity'],
                'indexes': [models.Index(fields=['item', 'name'], name='catalog_ite_item_id_cbd4c0_idx'), models.Index(fields=['barcode'], name='catalog_ite_barcode_4b416c_idx')],
            },
        ),
    ]
