# Generated by Django 5.2.12 on 2026-06-30 02:38

import catalog.models.item_image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_historicalitempackaging_itempackaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitemimage',
            name='image',
            field=models.TextField(help_text='Image file for the item', max_length=100, validators=[catalog.models.item_image.validate_item_file]),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(help_text='Image file for the item', upload_to=catalog.models.item_image.item_image_upload_path, validators=[catalog.models.item_image.validate_item_file]),
        ),
    ]
