# Generated by Django 5.2.12 on 2026-04-04 09:07

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_itemimage_options_and_more'),
        ('inventory', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInventoryMovement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Record status (active/inactive)', max_length=20)),
                ('document_no', models.CharField(db_index=True, help_text='Unique document number (Manual or Auto)', max_length=50)),
                ('type', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], help_text='Movement direction', max_length=20)),
                ('date', models.DateField(help_text='Transaction date')),
                ('note', models.TextField(blank=True, default='', help_text='General notes about this document')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, db_constraint=False, help_text='External partner (Supplier/Customer) involved', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.partner')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, help_text='Primary warehouse for this movement', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'historical Inventory Movement',
                'verbose_name_plural': 'historical Inventory Movements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Record status (active/inactive)', max_length=20)),
                ('document_no', models.CharField(db_index=True, help_text='Unique document number (Manual or Auto)', max_length=50, unique=True)),
                ('type', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], help_text='Movement direction', max_length=20)),
                ('date', models.DateField(help_text='Transaction date')),
                ('note', models.TextField(blank=True, default='', help_text='General notes about this document')),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, help_text='External partner (Supplier/Customer) involved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='partners.partner')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(help_text='Primary warehouse for this movement', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Inventory Movement',
                'verbose_name_plural': 'Inventory Movements',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalInventoryMovementAttachment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('document_file', models.TextField(help_text='Uploaded file (PDF, Image, etc.)', max_length=100)),
                ('file_name', models.CharField(blank=True, help_text='Original file name', max_length=255)),
                ('note', models.TextField(blank=True, default='', help_text='Optional remarks for this attachment')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('movement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventorymovement')),
            ],
            options={
                'verbose_name': 'historical Movement Attachment',
                'verbose_name_plural': 'historical Movement Attachments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InventoryMovementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('document_file', models.FileField(help_text='Uploaded file (PDF, Image, etc.)', upload_to='inventory/attachments/%Y/%m/')),
                ('file_name', models.CharField(blank=True, help_text='Original file name', max_length=255)),
                ('note', models.TextField(blank=True, default='', help_text='Optional remarks for this attachment')),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.inventorymovement')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movement Attachment',
                'verbose_name_plural': 'Movement Attachments',
            },
        ),
        migrations.CreateModel(
            name='InventoryMovementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(help_text='Batch/Lot number recorded at entry', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity moved', max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Unit cost at the time of movement', max_digits=12, null=True)),
                ('mfg_date', models.DateField(blank=True, help_text='Manufacturing Date (Draft phase entry)', null=True)),
                ('exp_date', models.DateField(blank=True, help_text='Expiry Date (Draft phase entry)', null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_items', to='catalog.item')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorymovement')),
            ],
            options={
                'verbose_name': 'Movement Item',
                'verbose_name_plural': 'Movement Items',
            },
        ),
    ]
