# Generated by Django 5.2.12 on 2026-04-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_historicalstockcard_stockcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventorymovement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', help_text='Document lifecycle status', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', help_text='Document lifecycle status', max_length=20),
        ),
    ]
