# Generated by Django 5.2.12 on 2026-04-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_historicalinventorymovement_reference_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventorymovement',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('production', 'Production Order'), ('stock_arrival', 'Stock Arrival Schedule'), ('other', 'Other')], default='none', help_text='External document category', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('production', 'Production Order'), ('stock_arrival', 'Stock Arrival Schedule'), ('other', 'Other')], default='none', help_text='External document category', max_length=50),
        ),
    ]
