# Generated by Django 5.2.12 on 2026-05-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_historicalinventorymovement_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventorymovement',
            name='document_no',
            field=models.CharField(db_index=True, help_text='Document number (Manual or Auto)', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='document_no',
            field=models.CharField(db_index=True, help_text='Document number (Manual or Auto)', max_length=50),
        ),
    ]
