# Generated by Django 5.2.12 on 2026-05-13 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_historicalinventorymovement_document_no_and_more'),
        ('procurement', '0003_alter_arrival_status_alter_historicalarrival_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovementitem',
            name='arrival_item',
            field=models.ForeignKey(blank=True, help_text='Link to source arrival line (for inbound receiving)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_items', to='procurement.arrivalitem'),
        ),
    ]
