# Generated by Django 5.2.12 on 2026-05-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventorymovementitem_arrival_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstock',
            name='reserved_qty',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Quantity reserved for sales orders or other commitments', max_digits=12),
        ),
        migrations.AddField(
            model_name='stock',
            name='reserved_qty',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Quantity reserved for sales orders or other commitments', max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current total quantity on hand for this specific lot', max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current total quantity on hand for this specific lot', max_digits=12),
        ),
    ]
