# Generated by Django 5.2.12 on 2026-05-13 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_historicalstock_reserved_qty_stock_reserved_qty_and_more'),
        ('procurement', '0004_alter_historicalshortage_reference_id_and_more'),
        ('sales', '0002_delete_salesallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_type', models.CharField(choices=[('sales_order', 'Sales Order'), ('production', 'Production'), ('internal', 'Internal Transfer'), ('hold', 'Quality/Maintenance Hold')], default='sales_order', max_length=20)),
                ('reference_no', models.CharField(help_text='Document number (e.g. SO-101)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='')),
                ('arrival_item', models.ForeignKey(blank=True, help_text='Reserved from future shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='procurement.arrivalitem')),
                ('sales_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='sales.salesorderitem')),
                ('stock', models.ForeignKey(blank=True, help_text='Reserved from physical shelf', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='inventory.stock')),
            ],
            options={
                'verbose_name': 'Stock Reservation',
                'verbose_name_plural': 'Stock Reservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
