# Generated by Django 5.2.12 on 2026-05-13 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_stockreservation'),
        ('sales', '0002_delete_salesallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockreservation',
            name='arrival_item',
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Physical quantity held', max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='sales_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical_reservations', to='sales.salesorderitem'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='stock',
            field=models.ForeignKey(help_text='The specific physical lot being locked', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.stock'),
        ),
    ]
