# Generated by Django 5.2.12 on 2026-05-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_stockreservation_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventorymovement',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('production', 'Production Order'), ('stock_arrival', 'Stock Arrival Schedule'), ('sales_order', 'Sales Order'), ('other', 'Other')], default='none', help_text='External document category', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('production', 'Production Order'), ('stock_arrival', 'Stock Arrival Schedule'), ('sales_order', 'Sales Order'), ('other', 'Other')], default='none', help_text='External document category', max_length=50),
        ),
    ]
