# Generated by Django 5.2.12 on 2026-05-29 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_stockreservation_deleted_at_and_more'),
        ('procurement', '0011_shortage_expected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstockreservation',
            name='origin_arrival_item',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The incoming shipment line that fulfilled this physical reservation hold', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.arrivalitem'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='origin_arrival_item',
            field=models.ForeignKey(blank=True, help_text='The incoming shipment line that fulfilled this physical reservation hold', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_reservations', to='procurement.arrivalitem'),
        ),
    ]
