# Generated by Django 5.2.12 on 2026-06-30 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_company_historicalcompany'),
        ('inventory', '0017_historicalstockreservation_origin_arrival_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwarehouse',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The company this warehouse belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='common.company'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(blank=True, help_text='The company this warehouse belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='common.company'),
        ),
    ]
