# Generated by Django 5.2.12 on 2026-04-03 04:41

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPartner',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Record status (active/inactive)', max_length=20)),
                ('name', models.CharField(db_index=True, help_text='Partner display name', max_length=200)),
                ('code', models.CharField(db_index=True, help_text='Unique partner code (e.g. VEND001, CUST001)', max_length=50)),
                ('is_supplier', models.BooleanField(default=False, help_text='Indicates if the partner is a supplier')),
                ('is_customer', models.BooleanField(default=False, help_text='Indicates if the partner is a customer')),
                ('tax_id', models.CharField(blank=True, default='', help_text='Tax identification number', max_length=50)),
                ('address', models.TextField(blank=True, default='', help_text='Full address details')),
                ('contact_name', models.CharField(blank=True, default='', help_text='Main contact person', max_length=100)),
                ('phone', models.CharField(blank=True, default='', help_text='Contact phone number', max_length=50)),
                ('email', models.EmailField(blank=True, default='', help_text='Contact email address', max_length=254)),
                ('note', models.TextField(blank=True, default='', help_text='Internal notes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Partner',
                'verbose_name_plural': 'historical Partners',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Record status (active/inactive)', max_length=20)),
                ('name', models.CharField(help_text='Partner display name', max_length=200, unique=True)),
                ('code', models.CharField(help_text='Unique partner code (e.g. VEND001, CUST001)', max_length=50, unique=True)),
                ('is_supplier', models.BooleanField(default=False, help_text='Indicates if the partner is a supplier')),
                ('is_customer', models.BooleanField(default=False, help_text='Indicates if the partner is a customer')),
                ('tax_id', models.CharField(blank=True, default='', help_text='Tax identification number', max_length=50)),
                ('address', models.TextField(blank=True, default='', help_text='Full address details')),
                ('contact_name', models.CharField(blank=True, default='', help_text='Main contact person', max_length=100)),
                ('phone', models.CharField(blank=True, default='', help_text='Contact phone number', max_length=50)),
                ('email', models.EmailField(blank=True, default='', help_text='Contact email address', max_length=254)),
                ('note', models.TextField(blank=True, default='', help_text='Internal notes')),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='partners_pa_code_758beb_idx'), models.Index(fields=['name'], name='partners_pa_name_057e86_idx')],
            },
        ),
    ]
