# Generated by Django 5.2.12 on 2026-05-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_arrivalattachment_historicalarrivalattachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrival',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('receiving', 'Receiving'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Current status of the shipment', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalarrival',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('receiving', 'Receiving'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Current status of the shipment', max_length=20),
        ),
    ]
