# Generated by Django 5.2.12 on 2026-05-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_alter_arrival_status_alter_historicalarrival_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshortage',
            name='reference_id',
            field=models.CharField(blank=True, default='', help_text='ID or document number of the source (e.g. Sell order #123)', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalshortage',
            name='reference_type',
            field=models.CharField(choices=[('sell_order', 'Sell Order'), ('production', 'Production'), ('other', 'Other')], default='other', help_text='The source of the demand', max_length=20),
        ),
        migrations.AlterField(
            model_name='shortage',
            name='reference_id',
            field=models.CharField(blank=True, default='', help_text='ID or document number of the source (e.g. Sell order #123)', max_length=100),
        ),
        migrations.AlterField(
            model_name='shortage',
            name='reference_type',
            field=models.CharField(choices=[('sell_order', 'Sell Order'), ('production', 'Production'), ('other', 'Other')], default='other', help_text='The source of the demand', max_length=20),
        ),
    ]
