# Generated by Django 5.2.12 on 2026-05-13 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_alter_historicalshortage_reference_id_and_more'),
        ('sales', '0003_salesallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity reserved from the incoming shipment', max_digits=12)),
                ('reference_no', models.CharField(help_text='Document number (e.g. SO-101)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='')),
                ('arrival_item', models.ForeignKey(help_text='The incoming shipment line being reserved', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='procurement.arrivalitem')),
                ('sales_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_reservations', to='sales.salesorderitem')),
            ],
            options={
                'verbose_name': 'Arrival Reservation',
                'verbose_name_plural': 'Arrival Reservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
