# Generated by Django 5.2.12 on 2026-05-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_arrivalreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalitem',
            name='reserved_qty',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Quantity committed to Sell Orders', max_digits=12),
        ),
    ]
