# Generated by Django 5.2.12 on 2026-05-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_arrivalitem_reserved_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalreservation',
            name='reference_type',
            field=models.CharField(choices=[('sales_order', 'Sales Order'), ('production', 'Production'), ('internal', 'Internal Transfer'), ('hold', 'Quality/Maintenance Hold')], default='sales_order', max_length=20),
        ),
    ]
