# Generated by Django 5.2.12 on 2026-05-18 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_historicalitempackaging_itempackaging'),
        ('procurement', '0007_arrivalreservation_reference_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalitem',
            name='packaging',
            field=models.ForeignKey(blank=True, help_text='Received packaging container (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_items', to='catalog.itempackaging'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='packaging',
            field=models.ForeignKey(blank=True, help_text='Ordered packaging container (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_items', to='catalog.itempackaging'),
        ),
    ]
