# Generated by Django 5.2.12 on 2026-05-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_arrivalitem_packaging_purchaseorderitem_packaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalitem',
            name='exp_date',
            field=models.DateField(blank=True, help_text='Expiry date', null=True),
        ),
        migrations.AddField(
            model_name='arrivalitem',
            name='mfg_date',
            field=models.DateField(blank=True, help_text='Manufacturing date', null=True),
        ),
    ]
