# Generated by Django 5.2.12 on 2026-05-21 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_arrivalitem_exp_date_arrivalitem_mfg_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalreservation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this arrival reservation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
