# Generated by Django 5.2.12 on 2026-05-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_arrivalreservation_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshortage',
            name='expected_date',
            field=models.DateField(blank=True, help_text='Date when the items are expected to be needed', null=True),
        ),
        migrations.AddField(
            model_name='shortage',
            name='expected_date',
            field=models.DateField(blank=True, help_text='Date when the items are expected to be needed', null=True),
        ),
    ]
