# Generated by Django 5.2.12 on 2026-05-29 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_shortage_expected_date'),
        ('sales', '0010_historicalsalesorderattachment_salesorderattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivalreservation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this arrival reservation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='arrivalreservation',
            name='sales_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_reservations', to='sales.salesorderitem'),
        ),
    ]
