# Generated by Django 5.2.12 on 2026-06-04 07:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_alter_arrivalreservation_created_by_and_more'),
        ('sales', '0012_alter_salesallocation_arrival_reservation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalreservation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True),
        ),
        migrations.AddField(
            model_name='arrivalreservation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arrivalreservation',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted'),
        ),
        migrations.AddField(
            model_name='arrivalreservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
        migrations.AddField(
            model_name='arrivalreservation',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arrivalreservation',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking'),
        ),
        migrations.AlterField(
            model_name='arrivalreservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='arrivalreservation',
            name='created_by',
            field=models.ForeignKey(default=1, help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HistoricalArrivalReservation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity reserved from the incoming shipment', max_digits=12)),
                ('reference_type', models.CharField(choices=[('sales_order', 'Sales Order'), ('production', 'Production'), ('internal', 'Internal Transfer'), ('hold', 'Quality/Maintenance Hold')], default='sales_order', max_length=20)),
                ('reference_no', models.CharField(help_text='Document number (e.g. SO-101)', max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('arrival_item', models.ForeignKey(blank=True, db_constraint=False, help_text='The incoming shipment line being reserved', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.arrivalitem')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sales_item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.salesorderitem')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Arrival Reservation',
                'verbose_name_plural': 'historical Arrival Reservations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
