# Generated by Django 5.2.12 on 2026-06-09 03:55

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_historicalitempackaging_itempackaging'),
        ('procurement', '0013_arrivalreservation_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when record was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arrivalitem',
            name='created_by',
            field=models.ForeignKey(default=1, help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arrivalitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True),
        ),
        migrations.AddField(
            model_name='arrivalitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arrivalitem',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted'),
        ),
        migrations.AddField(
            model_name='arrivalitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
        migrations.AddField(
            model_name='arrivalitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arrivalitem',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking'),
        ),
        migrations.CreateModel(
            name='HistoricalArrivalItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('expected_qty', models.DecimalField(decimal_places=2, help_text='Quantity expected according to shipment', max_digits=12)),
                ('received_qty', models.DecimalField(decimal_places=2, default=0.0, help_text='Actual quantity received in warehouse', max_digits=12)),
                ('reserved_qty', models.DecimalField(decimal_places=2, default=0.0, help_text='Quantity committed to Sell Orders', max_digits=12)),
                ('mfg_date', models.DateField(blank=True, help_text='Manufacturing date', null=True)),
                ('exp_date', models.DateField(blank=True, help_text='Expiry date', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('arrival', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.arrival')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.item')),
                ('packaging', models.ForeignKey(blank=True, db_constraint=False, help_text='Received packaging container (optional)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.itempackaging')),
                ('po_item', models.ForeignKey(blank=True, db_constraint=False, help_text='Link to specific PO line for fulfillment tracking', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.purchaseorderitem')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Arrival Item',
                'verbose_name_plural': 'historical Arrival Items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
