# Generated by Django 5.2.12 on 2026-06-10 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_historicalstockreservation_origin_arrival_item_and_more'),
        ('procurement', '0014_arrivalitem_created_at_arrivalitem_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalreservation',
            name='promoted_stock_reservation',
            field=models.ForeignKey(blank=True, help_text='The physical stock reservation created when this arrival line was received', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_sources', to='inventory.stockreservation'),
        ),
        migrations.AddField(
            model_name='arrivalreservation',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('cancelled', 'Cancelled'), ('promoted', 'Promoted')], default='reserved', help_text='Current lifecycle state of the reservation', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalarrivalreservation',
            name='promoted_stock_reservation',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The physical stock reservation created when this arrival line was received', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stockreservation'),
        ),
        migrations.AddField(
            model_name='historicalarrivalreservation',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('cancelled', 'Cancelled'), ('promoted', 'Promoted')], default='reserved', help_text='Current lifecycle state of the reservation', max_length=20),
        ),
    ]
