# Generated by Django 5.2.12 on 2026-06-10 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0015_arrivalreservation_promoted_stock_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshortage',
            name='promoted_arrival_reservation',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The arrival reservation created when this shortage was promoted', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.arrivalreservation'),
        ),
        migrations.AddField(
            model_name='shortage',
            name='promoted_arrival_reservation',
            field=models.ForeignKey(blank=True, help_text='The arrival reservation created when this shortage was promoted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_shortages', to='procurement.arrivalreservation'),
        ),
        migrations.AlterField(
            model_name='historicalshortage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('po_created', 'PO Created'), ('promoted', 'Promoted'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the shortage record', max_length=20),
        ),
        migrations.AlterField(
            model_name='shortage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('po_created', 'PO Created'), ('promoted', 'Promoted'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the shortage record', max_length=20),
        ),
    ]
