# Generated by Django 5.2.12 on 2026-04-04 08:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_itemimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWarehouse',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Record status (active/inactive)', max_length=20)),
                ('name', models.CharField(help_text='Warehouse display name', max_length=100)),
                ('code', models.CharField(db_index=True, help_text='Unique warehouse code (e.g. WH-001)', max_length=20)),
                ('note', models.TextField(blank=True, default='', help_text='Internal notes about this warehouse')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Warehouse',
                'verbose_name_plural': 'historical Warehouses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Record status (active/inactive)', max_length=20)),
                ('name', models.CharField(help_text='Warehouse display name', max_length=100)),
                ('code', models.CharField(db_index=True, help_text='Unique warehouse code (e.g. WH-001)', max_length=20, unique=True)),
                ('note', models.TextField(blank=True, default='', help_text='Internal notes about this warehouse')),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Record status (active/inactive)', max_length=20)),
                ('lot_number', models.CharField(db_index=True, help_text='Globally unique batch/lot ID', max_length=100, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current available quantity for this specific lot', max_digits=12)),
                ('mfg_date', models.DateField(blank=True, help_text='Manufacturing Date', null=True)),
                ('exp_date', models.DateField(blank=True, help_text='Expiry Date', null=True)),
                ('note', models.TextField(blank=True, default='', help_text='Internal notes about this batch')),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(help_text='Item in the catalog', on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.item')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(help_text='Warehouse where this stock is located', on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['-exp_date', 'lot_number'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalStock',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Record status (active/inactive)', max_length=20)),
                ('lot_number', models.CharField(db_index=True, help_text='Globally unique batch/lot ID', max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current available quantity for this specific lot', max_digits=12)),
                ('mfg_date', models.DateField(blank=True, help_text='Manufacturing Date', null=True)),
                ('exp_date', models.DateField(blank=True, help_text='Expiry Date', null=True)),
                ('note', models.TextField(blank=True, default='', help_text='Internal notes about this batch')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, help_text='Item in the catalog', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.item')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, help_text='Warehouse where this stock is located', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'historical Stock',
                'verbose_name_plural': 'historical Stocks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['code'], name='inventory_w_code_2cdc02_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['name'], name='inventory_w_name_703b74_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['lot_number'], name='inventory_s_lot_num_6fbc51_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['item', 'warehouse'], name='inventory_s_item_id_6bc180_idx'),
        ),
    ]
