# Generated by Django 5.2.12 on 2026-04-06 03:10

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_itemimage_options_and_more'),
        ('inventory', '0002_historicalinventorymovement_inventorymovement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStockCard',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('lot_number', models.CharField(help_text='Snapshot of the batch/lot number', max_length=100)),
                ('qty_in', models.DecimalField(decimal_places=2, default=0.0, help_text='Quantity added', max_digits=12)),
                ('qty_out', models.DecimalField(decimal_places=2, default=0.0, help_text='Quantity removed', max_digits=12)),
                ('note', models.TextField(blank=True, default='', help_text='Audit notes for this entry')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, help_text='Snapshot of the item at transaction time', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.item')),
                ('movement_item', models.ForeignKey(blank=True, db_constraint=False, help_text='Source movement line item', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventorymovementitem')),
                ('stock', models.ForeignKey(blank=True, db_constraint=False, help_text='The impacted stock balance record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stock')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, help_text='Snapshot of the warehouse at transaction time', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'historical Stock Card',
                'verbose_name_plural': 'historical Stock Cards',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StockCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('lot_number', models.CharField(help_text='Snapshot of the batch/lot number', max_length=100)),
                ('qty_in', models.DecimalField(decimal_places=2, default=0.0, help_text='Quantity added', max_digits=12)),
                ('qty_out', models.DecimalField(decimal_places=2, default=0.0, help_text='Quantity removed', max_digits=12)),
                ('note', models.TextField(blank=True, default='', help_text='Audit notes for this entry')),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(help_text='Snapshot of the item at transaction time', on_delete=django.db.models.deletion.CASCADE, related_name='stock_cards', to='catalog.item')),
                ('movement_item', models.ForeignKey(blank=True, help_text='Source movement line item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_cards', to='inventory.inventorymovementitem')),
                ('stock', models.ForeignKey(help_text='The impacted stock balance record', on_delete=django.db.models.deletion.CASCADE, related_name='stock_cards', to='inventory.stock')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(help_text='Snapshot of the warehouse at transaction time', on_delete=django.db.models.deletion.CASCADE, related_name='stock_cards', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Card',
                'verbose_name_plural': 'Stock Cards',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lot_number'], name='inventory_s_lot_num_cdf64f_idx'), models.Index(fields=['warehouse', 'item'], name='inventory_s_warehou_ce2ead_idx')],
            },
        ),
    ]
