# Generated by Django 5.2.12 on 2026-04-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_historicalinventorymovement_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstockcard',
            name='qty_in',
        ),
        migrations.RemoveField(
            model_name='historicalstockcard',
            name='qty_out',
        ),
        migrations.RemoveField(
            model_name='stockcard',
            name='qty_in',
        ),
        migrations.RemoveField(
            model_name='stockcard',
            name='qty_out',
        ),
        migrations.AddField(
            model_name='historicalstockcard',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Magnitude of change', max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalstockcard',
            name='type',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out')], default='in', help_text='Direction of change (in/out)', max_length=10),
        ),
        migrations.AddField(
            model_name='stockcard',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Magnitude of change', max_digits=12),
        ),
        migrations.AddField(
            model_name='stockcard',
            name='type',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out')], default='in', help_text='Direction of change (in/out)', max_length=10),
        ),
    ]
