# Generated by Django 5.2.12 on 2026-04-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_historicalstockcard_qty_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventorymovement',
            name='reference_no',
            field=models.CharField(blank=True, default='', help_text='ID/Number of the source document', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalinventorymovement',
            name='reference_type',
            field=models.CharField(choices=[('none', 'None'), ('production', 'Production Order'), ('stock_arrival', 'Stock Arrival Schedule'), ('other', 'Other')], default='none', help_text='External document category', max_length=50),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='reference_no',
            field=models.CharField(blank=True, default='', help_text='ID/Number of the source document', max_length=100),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='reference_type',
            field=models.CharField(choices=[('none', 'None'), ('production', 'Production Order'), ('stock_arrival', 'Stock Arrival Schedule'), ('other', 'Other')], default='none', help_text='External document category', max_length=50),
        ),
    ]
