# Generated by Django 5.2.12 on 2026-04-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_historicalinventorymovement_reference_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventorymovement',
            name='recipient',
            field=models.CharField(blank=True, default='', help_text='Recipient name (fallback for missing Partner records)', max_length=255),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='recipient',
            field=models.CharField(blank=True, default='', help_text='Recipient name (fallback for missing Partner records)', max_length=255),
        ),
    ]
