# Generated by Django 5.2.12 on 2026-05-13 07:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_historicalitem_name2_item_name2_and_more'),
        ('inventory', '0010_inventorymovementitem_arrival_item'),
        ('partners', '0001_initial'),
        ('procurement', '0003_alter_arrival_status_alter_historicalarrival_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSalesOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('document_no', models.CharField(db_index=True, help_text='SO-XXXX unique number', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('preorder', 'Pre-order'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('order_type', models.CharField(choices=[('normal', 'Normal Sale'), ('preorder', 'Pre-order')], default='normal', max_length=20)),
                ('order_date', models.DateField(blank=True, editable=False)),
                ('note', models.TextField(blank=True, default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, db_constraint=False, help_text='Customer record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.partner')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Sales Order',
                'verbose_name_plural': 'historical Sales Orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('document_no', models.CharField(db_index=True, help_text='SO-XXXX unique number', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('preorder', 'Pre-order'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('order_type', models.CharField(choices=[('normal', 'Normal Sale'), ('preorder', 'Pre-order')], default='normal', max_length=20)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(help_text='Customer record', on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='partners.partner')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Ordered quantity', max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit', max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_items', to='catalog.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder')),
            ],
            options={
                'verbose_name': 'Sales Order Item',
                'verbose_name_plural': 'Sales Order Items',
            },
        ),
        migrations.CreateModel(
            name='SalesAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('stock', 'Actual Stock (Physical)'), ('arrival', 'Incoming Arrival (Future)'), ('shortage', 'Shortage (To be purchased)')], default='shortage', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Allocated quantity', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arrival_item', models.ForeignKey(blank=True, help_text='Reserved from future shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_allocations', to='procurement.arrivalitem')),
                ('stock', models.ForeignKey(blank=True, help_text='Reserved from physical shelf', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_allocations', to='inventory.stock')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='sales.salesorderitem')),
            ],
            options={
                'verbose_name': 'Sales Allocation',
                'verbose_name_plural': 'Sales Allocations',
            },
        ),
    ]
