# Generated by Django 5.2.12 on 2026-05-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesAllocation',
        ),
    ]
