# Generated by Django 5.2.12 on 2026-05-13 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_stockreservation_arrival_item_and_more'),
        ('procurement', '0004_alter_historicalshortage_reference_id_and_more'),
        ('sales', '0002_delete_salesallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('stock', 'Actual Stock (Physical)'), ('arrival', 'Incoming Arrival (Future)'), ('shortage', 'Shortage (To be purchased)')], default='shortage', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Amount allocated from this source', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arrival_item', models.ForeignKey(blank=True, help_text='Reserved from future shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_allocations', to='procurement.arrivalitem')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='sales.salesorderitem')),
                ('physical_reservation', models.OneToOneField(blank=True, help_text='Link to the physical hold in the warehouse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_allocation', to='inventory.stockreservation')),
            ],
            options={
                'verbose_name': 'Sales Allocation',
                'verbose_name_plural': 'Sales Allocations',
            },
        ),
    ]
