# Generated by Django 5.2.12 on 2026-05-13 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_arrivalreservation'),
        ('sales', '0003_salesallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesallocation',
            name='arrival_item',
        ),
        migrations.AddField(
            model_name='salesallocation',
            name='arrival_reservation',
            field=models.OneToOneField(blank=True, help_text='Link to the future hold in procurement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_allocation', to='procurement.arrivalreservation'),
        ),
    ]
