# Generated by Django 5.2.12 on 2026-05-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_salesallocation_arrival_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='allocated_qty',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total quantity allocated (Physical + Future + Shortage)', max_digits=12),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='fulfilled_qty',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Quantity actually shipped from warehouse', max_digits=12),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='requested_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Original quantity requested by customer', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Allocation'), ('partial', 'Partially Allocated'), ('allocated', 'Fully Allocated'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
