# Generated by Django 5.2.12 on 2026-05-14 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_arrivalreservation_reference_type'),
        ('sales', '0005_remove_salesorderitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesallocation',
            name='shortage',
            field=models.OneToOneField(blank=True, help_text='Link to the shortage record in procurement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_allocation', to='procurement.shortage'),
        ),
    ]
