# Generated by Django 5.2.12 on 2026-05-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salesallocation_shortage'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesallocation',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='If True, the system will not auto-recalculate this allocation'),
        ),
    ]
