# Generated by Django 5.2.12 on 2026-05-18 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_salesallocation_is_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsalesorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
