# Generated by Django 5.2.12 on 2026-05-26 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_historicalsalesorder_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='is_manual_allocate',
            field=models.BooleanField(default=False, help_text='Designates whether this item has been manually allocated, bypassing automatic stock sourcing (FEFO)'),
        ),
        migrations.AlterField(
            model_name='historicalsalesorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Target timeline expected to fulfill the order'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Target timeline expected to fulfill the order'),
        ),
    ]
