# Generated by Django 5.2.12 on 2026-06-04 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_historicalstockreservation_origin_arrival_item_and_more'),
        ('procurement', '0012_alter_arrivalreservation_created_by_and_more'),
        ('sales', '0011_salesallocation_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesallocation',
            name='arrival_reservation',
            field=models.ForeignKey(blank=True, help_text='Link to the future hold in procurement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_allocations', to='procurement.arrivalreservation'),
        ),
        migrations.AlterField(
            model_name='salesallocation',
            name='physical_reservation',
            field=models.ForeignKey(blank=True, help_text='Link to the physical hold in the warehouse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_allocations', to='inventory.stockreservation'),
        ),
        migrations.AlterField(
            model_name='salesallocation',
            name='shortage',
            field=models.ForeignKey(blank=True, help_text='Link to the shortage record in procurement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_allocations', to='procurement.shortage'),
        ),
    ]
