# Generated by Django 5.2.12 on 2026-06-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_salesallocation_arrival_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalesorder',
            name='customer_po_no',
            field=models.CharField(blank=True, help_text='Customer PO number (non-unique reference)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalsalesorder',
            name='invoice_no',
            field=models.CharField(blank=True, help_text='Invoice number reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_po_no',
            field=models.CharField(blank=True, help_text='Customer PO number (non-unique reference)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='invoice_no',
            field=models.CharField(blank=True, help_text='Invoice number reference', max_length=100, null=True),
        ),
    ]
