# Generated by Django 5.2.12 on 2026-07-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_historicalindividual_individual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'ordering': ['first_name_th', 'last_name_th'], 'verbose_name': 'Individual', 'verbose_name_plural': 'Individuals'},
        ),
        migrations.RemoveField(
            model_name='historicalindividual',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='historicalindividual',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='last_name',
        ),
        migrations.AddField(
            model_name='historicalindividual',
            name='first_name_en',
            field=models.CharField(blank=True, default='', help_text='First name in English', max_length=150),
        ),
        migrations.AddField(
            model_name='historicalindividual',
            name='first_name_th',
            field=models.CharField(default='', help_text='First name in Thai', max_length=150),
        ),
        migrations.AddField(
            model_name='historicalindividual',
            name='last_name_en',
            field=models.CharField(blank=True, default='', help_text='Last name in English', max_length=150),
        ),
        migrations.AddField(
            model_name='historicalindividual',
            name='last_name_th',
            field=models.CharField(default='', help_text='Last name in Thai', max_length=150),
        ),
        migrations.AddField(
            model_name='historicalindividual',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='Nickname (Thai or English)', max_length=50),
        ),
        migrations.AddField(
            model_name='individual',
            name='first_name_en',
            field=models.CharField(blank=True, default='', help_text='First name in English', max_length=150),
        ),
        migrations.AddField(
            model_name='individual',
            name='first_name_th',
            field=models.CharField(default='', help_text='First name in Thai', max_length=150),
        ),
        migrations.AddField(
            model_name='individual',
            name='last_name_en',
            field=models.CharField(blank=True, default='', help_text='Last name in English', max_length=150),
        ),
        migrations.AddField(
            model_name='individual',
            name='last_name_th',
            field=models.CharField(default='', help_text='Last name in Thai', max_length=150),
        ),
        migrations.AddField(
            model_name='individual',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='Nickname (Thai or English)', max_length=50),
        ),
    ]
