# Dockerfile
FROM python:3.13.5-slim-bullseye

COPY  ./srcs /app

COPY requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]