# Generated by Django 5.2.12 on 2026-04-09 02:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_itemimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='name2',
            field=models.CharField(blank=True, default='', help_text='Secondary display name (e.g. English name from STKDES2)', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='name2',
            field=models.CharField(blank=True, default='', help_text='Secondary display name (e.g. English name from STKDES2)', max_length=200),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name2'], name='catalog_ite_name2_b6463e_idx'),
        ),
    ]
