# Generated by Django 5.2.12 on 2026-07-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petty_cash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpettycashaccount',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Optional remarks for this account'),
        ),
        migrations.AddField(
            model_name='historicalpettycashcategory',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Optional remarks for this category'),
        ),
        migrations.AddField(
            model_name='historicalpettycashpayment',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Optional remarks for this payment'),
        ),
        migrations.AddField(
            model_name='pettycashaccount',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Optional remarks for this account'),
        ),
        migrations.AddField(
            model_name='pettycashcategory',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Optional remarks for this category'),
        ),
        migrations.AddField(
            model_name='pettycashpayment',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Optional remarks for this payment'),
        ),
        migrations.AddField(
            model_name='pettycashpaymentitem',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Optional remarks for this item'),
        ),
    ]
