# Generated by Django 5.2.12 on 2026-07-06 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petty_cash', '0002_historicalpettycashaccount_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpettycashpayment',
            name='is_posted',
            field=models.BooleanField(default=False, help_text='Designates whether this voucher has been posted/recorded in Express ERP.'),
        ),
        migrations.AddField(
            model_name='historicalpettycashpayment',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpettycashpayment',
            name='posted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashpayment',
            name='is_posted',
            field=models.BooleanField(default=False, help_text='Designates whether this voucher has been posted/recorded in Express ERP.'),
        ),
        migrations.AddField(
            model_name='pettycashpayment',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pettycashpayment',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pettycashpaymentitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Bilingual category with accounting code mapping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_items', to='petty_cash.pettycashcategory'),
        ),
    ]
